# Generated by Django 4.2.13 on 2024-06-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cycle',
        ),
    ]
